###################################################################
## The makeCacheMatrix function will read a matrix x 
## (the matrix must be square) and make it available to
## the cacheSolve function which calculates and return its inverse
###################################################################

########### How to use #################
##                                    ##
##    > aMatrix<-makeCacheMatrix(x)   ##
##    > cacheSolve(aMatrix)           ##
##                                    ##
##    will return the inverse of x    ##
##                                    ##
########################################



################## makeCacheMatrix #############################

## matrix x is read in (default=empty matrix)
makeCacheMatrix <- function(x = matrix()) {

## set the inverse matrix variable to NULL
  inv_m <-NULL
  
## setter function of aMatrix to asign a new value to aMatrix
## also resets any inverse matrix in store to NULL
    set <-function(y) {
        x<<-y
        inv_m<<-NULL
    }
##  getter function of aMatrix; returns what is currently stored in aMatrix
    get <-function() x

## setter and getter functions of the inverse matrix
    set_inv <-function(solve) inv_m <<- solve
    get_inv <-function() inv_m

## store functions in a named list and return to aMatrix
    list(set=set,get=get,set_inv=set_inv, get_inv=get_inv)
    
}

################## cacheSolve #############################

## matrix x and additional optional arguments are read in
cacheSolve <- function(x, ...) {

## get inv_m generated by makeCacheMatrix function         
    inv_m <- x$get_inv()

## If inv_m is not NULL, return inv_m    
    if(!is.null(inv_m)) {
        message ("getting cached data")
      return(inv_m)
    }
    
## Else get the matrix currently stored in aMatrix and store as data   
    data<-x$get()
## Assign the inverse of the matrix to inv_m
    inv_m<-solve(data,...)
## Assign the new inverse matrix to the global inv_m variable 
    x$set_inv(inv_m) 
## return the inverse matrix
    inv_m
}
